<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.8.5 on linux)" generated="20201102 17:13:07.560" rpa="false">
<suite id="s1" name="Foo" source="/home/tkacza/AAA/programing/DormNotebooks/robot/Tests/foo.robot">
<test id="s1-t1" name="foo aaaaaaaaaa">
<kw name="log in" library="res1" type="setup">
<arguments>
<arg>mieczyslawa</arg>
</arguments>
<kw name="Open Browser">
<arguments>
<arg>http://0.0.0.0:8000</arg>
<arg>firefox</arg>
</arguments>
<msg timestamp="20201102 17:13:07.613" level="FAIL">No keyword with name 'Open Browser' found.</msg>
<status status="FAIL" starttime="20201102 17:13:07.612" endtime="20201102 17:13:07.613"></status>
</kw>
<status status="FAIL" starttime="20201102 17:13:07.610" endtime="20201102 17:13:07.613"></status>
</kw>
<status status="FAIL" starttime="20201102 17:13:07.610" endtime="20201102 17:13:07.613" critical="yes">Setup failed:
No keyword with name 'Open Browser' found.</status>
</test>
<status status="FAIL" starttime="20201102 17:13:07.561" endtime="20201102 17:13:07.613"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Foo">Foo</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20201102 17:13:07.580" level="ERROR">Error in file '/home/tkacza/AAA/programing/DormNotebooks/robot/Tests/foo.robot' on line 2: Importing test library 'SeleniumLibrary' failed: ModuleNotFoundError: No module named 'SeleniumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  /home/tkacza/AAA/programing/DormNotebooksVenv/bin
  /usr/lib/python38.zip
  /usr/lib/python3.8
  /usr/lib/python3.8/lib-dynload
  /home/tkacza/AAA/programing/DormNotebooksVenv/lib/python3.8/site-packages</msg>
<msg timestamp="20201102 17:13:07.609" level="ERROR">Error in file '/home/tkacza/AAA/programing/DormNotebooks/robot/Resources/res1.robot' on line 2: Importing test library 'SeleniumLibrary' failed: ModuleNotFoundError: No module named 'SeleniumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  /home/tkacza/AAA/programing/DormNotebooksVenv/bin
  /usr/lib/python38.zip
  /usr/lib/python3.8
  /usr/lib/python3.8/lib-dynload
  /home/tkacza/AAA/programing/DormNotebooksVenv/lib/python3.8/site-packages</msg>
</errors>
</robot>
